["$globals"]
vars = [
    {
        "pytest_args"= "-vv --cov=src/",
        "pytest_path"= "tests/"
    },
]

[format]
phony = true
commands = [
    "isort --recursive .",
    "black .",
]

[lint]
phony = true
commands = [
    "flake8",
    "isort --check-only --recursive .",
    "black --check .",
]

[tests]
phony = true
commands = [
    "pytest ${pytest_args} ${pytest_path}"
]
