["$globals"]
vars = [
    {"pytest_args" = "-vv --cov=src/"},
    {"pytest_path" = "tests/"},
    {"poetry_extra" = ""},
]

[all]
alias = "install"

[install]
phony = true
keep_ts = true
requires = ["requirements.txt"]
commands = [
    "poetry install ${poetry_extra}",
]

[format]
phony = true
requires = ["install"]
commands = [
    "isort .",
    "black .",
]

[lint]
phony = true
requires = ["install"]
commands = [
    "flake8 .",
    "isort --check .",
    "black --check .",
]

[tests]
phony = true
requires = ["install"]
commands = [
    "pytest ${pytest_args} ${pytest_path}",
]

["poetry.lock"]
requires = ["pyproject.toml"]
commands = [
    "poetry lock && touch ${.target}",
]

["requirements.txt"]
requires = ["poetry.lock"]
commands = [
    "poetry export --without-hashes -f requirements.txt -o ${.target}",
]
