name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - uses: Gr1N/setup-poetry@v8
    - uses: actions/cache@v3
      with:
        path: ~/.cache/pypoetry/virtualenvs
        key: ${{ runner.os }}-3.11-poetry-${{ hashFiles('pyproject.toml') }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel
        pip install yamk
        yam install
    - name: Lint the project
      run: |
        yam lint
